# Generated by Django 6.0.1 on 2026-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('faculty', models.CharField(max_length=255)),
                ('department_program', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='students/')),
                ('academic_year', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
