# Generated by Django 6.0.1 on 2026-01-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_academic_year_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
