# Generated by Django 6.0.1 on 2026-01-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='issued_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
