# Generated by Django 6.0.3 on 2026-03-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_issued_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('photo', models.ImageField(upload_to='staff/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='staff_qrcodes/')),
                ('confirmed', models.BooleanField(default=False)),
                ('issued_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
