# Generated by Django 6.0.3 on 2026-03-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='qr_code',
        ),
    ]
