# Generated by Django 6.0.3 on 2026-03-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_staff_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='date_of_birth',
        ),
    ]
